package handlers

import (
	"github.com/gofiber/fiber/v2"
)

// Description:

// Takes in a JSON receipt (see example in the example directory) and returns a JSON object with an ID generated by your code.

// The ID returned is the ID that should be passed into `/receipts/{id}/points` to get the number of points the receipt
// was awarded.

// How many points should be earned are defined by the rules below.

// Reminder: Data does not need to survive an application restart. This is to allow you to use in-memory solutions to track any data generated by this endpoint.

// Example Response:
// ```json
// { "id": "7fb1377b-b223-49d9-a31a-5a02701dd310" }
// ```

// ProcessReceipt handles POST /receipts/process
// returns a JSON object with an ID generated by your code.
func ProcessReceipt(c *fiber.Ctx) error {
	// TODO: Implement receipt processing logic using Fiber's context
	return nil
}

// GetReceiptPoints handles GET /receipts/{id}/points
func GetReceiptPoints(c *fiber.Ctx) error {
	// TODO: Implement points retrieval logic using Fiber's context
	return nil
}
